### PR TITLE
Feature: Use user-provided Issuer/ClusterIssuer to generate TLS certs

### LINKED ISSUE #270: Use predefined ClusterIssuer to generate TLS certs (Configurable issuerRef)
**Is your feature request related to a problem? Please describe.**

We have a predefined `ClusterIssuer` and want to use it to issue TLS certs for controllers and peers. The current behavior is to auto-generate a new `ClusterIssuer` with self-signed CA for each `KafkaCluster`.
 
**Describe the solution you'd like to see**

From user's point of view, just add `issuerRef` entry to `listenersConfig` in `KafkaCluster` CRD.

```yaml
listenersConfig:
  sslSecrets:
    tlsSecretName: "example-kafka-operator"
    jksPasswordName: "example-kafka-operator-pass"
    create: true
    issuerRef:
      name: my-issuer
      kind: ClusterIssuer
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by YanzheL**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #270
| License         | Apache 2.0

### What's in this PR?

1. The current behavior of `kafka-operator` is to generate a new self-signed CA and encapsulate it as a `ClusterIssuer` for each `KafkaCluster` if no CA provided by user. User has to trust each CA for each cluster, which brings inconvenience and security concerns.

   This PR enables user to reuse a pre-defined cert-manager `Issuer/ClusterIssuer` to issue all TLS certs used by `kafka-operator` and `KafkaUser` when SSL is enabled.

   For example, I have a `ClusterIssuer` named `my-issuer-that-already-exists` and I want to reuse it. The configuration of `KafkaCluster` resource looks like this.

   ```yaml
   listenersConfig:
     sslSecrets:
       tlsSecretName: "example-kafka-operator"
       jksPasswordName: "example-kafka-operator-pass"
       create: true
       issuerRef:      # <--- New property
         name: my-issuer-that-already-exists
         kind: ClusterIssuer
   ```

2. Add "client auth" key usage to `KafkaUser` certs.

   The default value for `CertificateSpec.Usages` is `UsageServerAuth`, which is not enough for Kafka TLS client authentication. Lacking "client auth" will lead to continuously SSL handshake failure.
   I've seen this error multiple times, and it prevents brokers to boot.

### Additional context

In enterprise environment, the CA private key will not be exposed to a user (I mean the maintainer of a kafka cluster). So the kafka admin cannot provide a k8s secret that contains `caCert` and `caKey` for a `KafkaCluster` resource. The appropriate  way to obtain a trusted certificate is through a pre-defined issuer (Usually a cluster-wide CA). Clients are only needed to trust the single CA of the issuer. 

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [ ] User guide and development docs updated (if needed)

### CODE REVIEW

**Comment by YanzheL** [comment]
What does this CI error mean? I didn't touch these license files....

```shell
#!/bin/bash -eo pipefail
make license-check
bin/licensei check
github.com/sirupsen/logrus: no license file found
github.com/spf13/cast: no license file found
github.com/magiconair/properties: no license file found
github.com/pelletier/go-toml: no license file found
github.com/spf13/afero: no license file found
github.com/spf13/jwalterweatherman: no license file found
github.com/spf13/viper: no license file found
github.com/banzaicloud/bank-vaults/pkg/sdk: no license file found
github.com/go-logr/zapr: no license file found
github.com/prometheus/common: no license file found
github.com/lestrrat-go/backoff: no license file found
Makefile:54: recipe for target 'license-check' failed
make: *** [license-check] Error 2

Exited with code exit status 2
```

**Comment by baluchicken** [comment]
I just rekicked the CI and now it seems to pass the licence check. I guess some circle error.

**Comment by baluchicken** [comment]
Thanks for the contribution, now there is a lint error. Also can you please update the cluster CRD in the helm chart as well. https://github.com/banzaicloud/kafka-operator/blob/master/charts/kafka-operator/templates/operator-kafka-crd.yaml (No need to bump the version just. we will do that in case of a release)
Otherwise LGTM.

**Comment by YanzheL** [comment]
Thanks for your comment. I updated these files.

**Pull request merged**
