### PR TITLE
Migrate to envoy API V3 in Envoy Ingress

### LINKED ISSUE #597: Add support for more recent envoy builds
We have to update our envoy dependency.
This is required to support more recent envoy builds.
The generated config contains deprecated fields which are completely removed from the new versions.

In this task we should:
- Update the envoyproxy image to the latest available
- Update the envoy dependency to the latest available
- Update the envoy configuration file generated for external access

### PR DESCRIPTION
**Pull request by amuraru**
| Q                        | A|
| --------------- | ---|
| Bug fix?             | no|
| New feature?    | yes|
| API breaks?       | no|
| Deprecations?  | no|
| Related tickets | fixes #597|
| License             | Apache 2.0|

### What's in this PR?

- Update the envoy configuration file generated for external access using envoy api V3
- Update the envoy dependency to the latest 1.18.3

### Why?

kafka-operator is using envoyapi v2 to generate the envoy proxy configuration file.
Starting with envoy 17 envoy api v2 was removed and not available any more.

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

### CODE REVIEW

**Comment by amuraru** [comment]
retest this please

**Comment by amuraru** [comment]
something's wrong with the PR description but not sure what.
@baluchicken please help :)

**Comment by baluchicken** [comment]
> something's wrong with the PR description but not sure what.
> @baluchicken please help :)

Just fixed will check the PR soon:)

**Review by baluchicken — APPROVED** [review]
Thanks very much @amuraru. LGTM

**Review by hi-im-aren — APPROVED** [review]

**Pull request merged**
