### PR TITLE
Ignore all projects with conflicting licenses

### PR DESCRIPTION
**Pull request by jiayushe**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | NA
| License         | Apache 2.0

### What's in this PR?

Fix failing licensei check by ignoring all projects with conflicting licenses in `.licensei.toml`.

### Why?

The licensei check has been failing in master branch. Circle-ci is passing because it has been reading from a cache.
```
Found a cache from build 1982 at licensei-v3-9kw4StNgDUezjZkyXoR1xcM9ACK_xZmr6d7lWFGlXLI=
Size: 2.1 KiB
Cached paths:
  * /home/circleci/project/.licensei.cache
```

### Checklist

- [x] Implementation tested

### CODE REVIEW

**Comment by stoader** [comment]
Closing this PR as #429 fixes the license check issue.

**Comment by jiayushe** [comment]
Hi @stoader , I am not sure how #429 fixes this as the license check is also failing locally, not just in ci.

**Comment by stoader** [comment]
@jiayushe when you build it locally you need to provide your GH token through the GITHUB_TOKEN env var

eg. 
GITHUB_TOKEN=<your_gh_personal_access_token> make license-cache
GITHUB_TOKEN=<your_gh_personal_access_token> make license-check

The GH token is needed due to https://github.com/goph/licensei#github-authentication

**Comment by jiayushe** [comment]
Hi @stoader, thanks a lot for the explanation! Maybe this info can be added to the developer guide?

**Pull request closed without merging**
