### PR TITLE
Adding sidecar feature to KafkaOperator

### PR DESCRIPTION
**Pull request by adapured**
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no |
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |

What's in this PR?

Adding sidecar features to kafka operator.
Enabling the required volumes and environment variables.

Why?

Better to have Sidecar enabling feature.

Checklist

[x] Implementation tested
[x] Error handling code meets the guideline
[x] Logging code meets the guideline
[x] User guide and development docs updated (if needed)

### CODE REVIEW

**Comment by adapured** [comment]
retest

**Comment by adapured** [comment]
@baluchicken : indent changed to nindent. Please verify.

**Review by baluchicken — APPROVED** [review]

**Review by adamantal — APPROVED** [review]
LGTM, @amuraru can you review this PR too?

**Comment by amuraru** [comment]
Lgtm - thanks for your contribution

**Pull request merged**
